
//! Autogenerated weights for `pallet_content`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-03-31, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `akalabeth`, CPU: `AMD Ryzen 7 6800HS Creator Edition`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/jbrown/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/acuity-runtime/acuity_runtime.wasm
// --all
// --steps
// 50
// --repeat
// 20
// --template
// templates/runtime-weight-template.hbs
// --output
// src/weights
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};

pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_content::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `Content::ItemState` (r:1 w:1)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn publish_item(
		_parents: u32, _links: u32, _mentions: u32,
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3550`
		// Minimum execution time: 16_521_000 picoseconds.
		Weight::from_parts(17_974_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Content::ItemState` (r:1 w:1)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn publish_revision(
		_links: u32, _mentions: u32,
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3550`
		// Minimum execution time: 15_830_000 picoseconds.
		Weight::from_parts(16_751_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Content::ItemState` (r:1 w:1)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn retract_item(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3550`
		// Minimum execution time: 12_133_000 picoseconds.
		Weight::from_parts(13_255_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Content::ItemState` (r:1 w:1)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn set_not_revisionable(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3550`
		// Minimum execution time: 12_102_000 picoseconds.
		Weight::from_parts(13_265_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Content::ItemState` (r:1 w:1)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn set_not_retractable(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `118`
		//  Estimated: `3550`
		// Minimum execution time: 12_554_000 picoseconds.
		Weight::from_parts(13_325_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
