
//! Autogenerated weights for `pallet_account_content`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `akalabeth`, CPU: `AMD Ryzen 7 6800HS Creator Edition`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/acuity-runtime/acuity_runtime.wasm
// --all
// --steps
// 50
// --repeat
// 20
// --template
// templates/runtime-weight-template.hbs
// --output
// src/weights
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};

pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_account_content::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `AccountContent::AccountItemIdIndex` (r:1 w:1)
	/// Proof: `AccountContent::AccountItemIdIndex` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Content::ItemState` (r:1 w:0)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `AccountContent::AccountItemIds` (r:1 w:1)
	/// Proof: `AccountContent::AccountItemIds` (`max_values`: None, `max_size`: Some(32818), added: 35293, mode: `MaxEncodedLen`)
	fn add_item(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `35100`
		//  Estimated: `36283`
		// Minimum execution time: 101_370_000 picoseconds.
		Weight::from_parts(125_395_000, 36283)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountContent::AccountItemIdIndex` (r:1 w:2)
	/// Proof: `AccountContent::AccountItemIdIndex` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Content::ItemState` (r:1 w:0)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `AccountContent::AccountItemIds` (r:1 w:1)
	/// Proof: `AccountContent::AccountItemIds` (`max_values`: None, `max_size`: Some(32818), added: 35293, mode: `MaxEncodedLen`)
	fn remove_item(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `35304`
		//  Estimated: `36283`
		// Minimum execution time: 108_313_000 picoseconds.
		Weight::from_parts(125_826_000, 36283)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}
