
//! Autogenerated weights for `pallet_balances`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `akalabeth`, CPU: `AMD Ryzen 7 6800HS Creator Edition`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/acuity-runtime/acuity_runtime.wasm
// --all
// --steps
// 50
// --repeat
// 20
// --template
// templates/runtime-weight-template.hbs
// --output
// src/weights
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};

pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_balances::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn transfer_allow_death(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 55_504_000 picoseconds.
		Weight::from_parts(56_415_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn transfer_keep_alive(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 47_879_000 picoseconds.
		Weight::from_parts(48_531_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_set_balance_creating(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 25_237_000 picoseconds.
		Weight::from_parts(25_828_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_set_balance_killing(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3569`
		// Minimum execution time: 26_129_000 picoseconds.
		Weight::from_parts(26_700_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_transfer(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `6148`
		// Minimum execution time: 57_829_000 picoseconds.
		Weight::from_parts(60_654_000, 6148)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn transfer_all(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 59_742_000 picoseconds.
		Weight::from_parts(60_854_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_unreserve(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3569`
		// Minimum execution time: 22_041_000 picoseconds.
		Weight::from_parts(22_803_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:999 w:999)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 1000]`.
	fn upgrade_accounts(
u: u32, 	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + u * (111 ±0)`
		//  Estimated: `990 + u * (2579 ±0)`
		// Minimum execution time: 22_021_000 picoseconds.
		Weight::from_parts(22_622_000, 990)
			// Standard Error: 14_099
			.saturating_add(Weight::from_parts(17_060_129, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(u.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(u.into())))
			.saturating_add(Weight::from_parts(0, 2579).saturating_mul(u.into()))
	}
	fn force_adjust_total_issuance(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_353_000 picoseconds.
		Weight::from_parts(7_734_000, 0)
	}
	fn burn_allow_death(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 32_551_000 picoseconds.
		Weight::from_parts(33_362_000, 0)
	}
	fn burn_keep_alive(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 24_917_000 picoseconds.
		Weight::from_parts(25_378_000, 0)
	}
}
