
//! Autogenerated weights for `pallet_balances`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-03-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `akalabeth`, CPU: `AMD Ryzen 7 6800HS Creator Edition`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/acuity-runtime/acuity_runtime.wasm
// --all
// --steps
// 50
// --repeat
// 20
// --template
// templates/runtime-weight-template.hbs
// --output
// src/weights
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};

pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_balances::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn transfer_allow_death(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 45_465_000 picoseconds.
		Weight::from_parts(48_310_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn transfer_keep_alive(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 39_504_000 picoseconds.
		Weight::from_parts(41_307_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_set_balance_creating(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 19_907_000 picoseconds.
		Weight::from_parts(21_240_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_set_balance_killing(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3569`
		// Minimum execution time: 21_400_000 picoseconds.
		Weight::from_parts(22_923_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_transfer(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `6148`
		// Minimum execution time: 49_283_000 picoseconds.
		Weight::from_parts(51_818_000, 6148)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn transfer_all(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3569`
		// Minimum execution time: 48_702_000 picoseconds.
		Weight::from_parts(52_378_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn force_unreserve(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3569`
		// Minimum execution time: 17_473_000 picoseconds.
		Weight::from_parts(19_056_000, 3569)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `System::Account` (r:999 w:999)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 1000]`.
	fn upgrade_accounts(
u: u32, 	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + u * (111 ±0)`
		//  Estimated: `990 + u * (2579 ±0)`
		// Minimum execution time: 18_455_000 picoseconds.
		Weight::from_parts(18_585_000, 990)
			// Standard Error: 8_820
			.saturating_add(Weight::from_parts(14_603_639, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(u.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(u.into())))
			.saturating_add(Weight::from_parts(0, 2579).saturating_mul(u.into()))
	}
	fn force_adjust_total_issuance(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_942_000 picoseconds.
		Weight::from_parts(6_643_000, 0)
	}
	fn burn_allow_death(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 28_324_000 picoseconds.
		Weight::from_parts(29_786_000, 0)
	}
	fn burn_keep_alive(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 21_310_000 picoseconds.
		Weight::from_parts(22_321_000, 0)
	}
}
