
//! Autogenerated weights for `pallet_content_reactions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `akalabeth`, CPU: `AMD Ryzen 7 6800HS Creator Edition`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/acuity-runtime/acuity_runtime.wasm
// --all
// --steps
// 50
// --repeat
// 20
// --template
// templates/runtime-weight-template.hbs
// --output
// src/weights
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::{constants::RocksDbWeight, Weight}};

pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_content_reactions::weights::WeightInfo for WeightInfo<T> {
	/// Storage: `Content::ItemState` (r:1 w:0)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ContentReactions::ItemAccountReactions` (r:1 w:1)
	/// Proof: `ContentReactions::ItemAccountReactions` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	fn add_reaction(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `326`
		//  Estimated: `3646`
		// Minimum execution time: 22_923_000 picoseconds.
		Weight::from_parts(23_504_000, 3646)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Content::ItemState` (r:1 w:0)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `ContentReactions::ItemAccountReactions` (r:1 w:1)
	/// Proof: `ContentReactions::ItemAccountReactions` (`max_values`: None, `max_size`: Some(181), added: 2656, mode: `MaxEncodedLen`)
	fn remove_reaction(
	) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `331`
		//  Estimated: `3646`
		// Minimum execution time: 22_572_000 picoseconds.
		Weight::from_parts(23_363_000, 3646)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
